### PR TITLE
Added more user input validation

### PR DESCRIPTION
**Pull request by larsenio72**
-For the time, date, and latitude/longitude
-Not sure how to make sure the correct number of digits have been inputted, just the values

### CODE REVIEW

**Comment by nhICS314** [comment]
You have to follow the example. The date asks for the month day and year separately so you enter 
07
31
2016

The time is in military time so if you want 2 pm you enter 
1400

For the latitude and longitude you can copy and paste the google maps coordinates separately like
25.876567
-127.654567
Google maps has the lat and long coordinates up to 6 decimal places which is what the iCal guides accept. 

Nicole Hanabusa

**Comment by larsenio72** [comment]
Are there merging errors with my update? The error checking works on my Eclipse and also processes successfully on Google Calendar.

**Comment by nhICS314** [comment]
I am going to have to take a look at it later it won't let me merge it with the master because it says there are conflicts.  So for the check in tomorrow I will probably just use what I have already in the repository.  This can be part of the next check in.

**Comment by larsenio72** [comment]
ok thank you! for the JUnit, what else should we test for because it seems the FindTimeZone function is the only thing we can check for the program returns properly.

**Comment by nhICS314** [comment]
Yeah that's why I chose that method to test. But in the event class you could set a variable and confirm it was set by using the same JUnit testing method

Nicole Hanabusa

**Pull request closed without merging**
